name: jusaimpulse_app
description: Aplicación móvil JusaImpulse MKT - Gestión de asignaciones y fotos
publish_to: 'none' # No publicar en pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Gestión de persistencia local (Necesaria para el cronómetro de 5 min)
  shared_preferences: ^2.2.2

  # Ubicación y GPS
  geolocator: ^10.1.0

  # Procesamiento de imágenes
  image: ^4.1.3

  # Rutas y archivos
  path_provider: ^2.1.1
  path: ^1.8.3

  # Íconos y diseño
  cupertino_icons: ^1.0.5

  # Peticiones HTTP
  http: ^1.1.0

  # Cámara y Galería
  image_picker: ^0.8.7+5

  # Logs y depuración
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # Assets de la app
  assets:
    - assets/images/logo-jusa-2-opt.png