name: jusaimpulse_app
description: Aplicación móvil JusaImpulse MKT - Gestión de asignaciones y fotos
publish_to: 'none' # No publicar en pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0      # <--- Agrega esta
  image: ^4.1.3            # <--- Agrega esta
  path_provider: ^2.1.1    # <--- Agrega esta
  
  # Íconos y diseño
  cupertino_icons: ^1.0.5

  # HTTP requests
  http: ^1.1.0

  # Tomar fotos
  image_picker: ^0.8.7+5

  # Logs
  logger: ^2.3.0

  # Guardar archivos localmente (opcional pero útil para fotos)  
  path: ^1.8.3  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # Assets de la app
  assets:
    - assets/images/logo-jusa-2-opt.png
