name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código fuente
      - name: Checkout source
        uses: actions/checkout@v3

      # 2. Instalar Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'   # tu versión estable

      # 3. Instalar dependencias
      - name: Install dependencies
        run: flutter pub get

      # 4. Compilar APK
      - name: Build APK
        run: flutter build apk --release

      # 5. Compilar AppBundle (AAB)
      - name: Build AppBundle
        run: flutter build appbundle --release

      # 6. Subir APK como artefacto
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # 7. Subir AAB como artefacto
      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
